Cargo.lock
Cargo.toml
README.md
migrations/2022-09-25-154001_add-veranstaltung/down.sql
migrations/2022-09-25-154001_add-veranstaltung/up.sql
src/bin/server/main.rs
src/lib.rs
src/models.rs
src/schema.rs
src/tucan.rs
src/tucan_user.rs
src/url.rs

Fetch Veranstaltungen

---

README.md

This PR updates the REAME.md to better reflect and fix the issues encountered during installation. This might still be incomplete, but should cover a wider base of potential cases.

Update readme install and dev entries

---

backend-rust/Cargo.toml
backend-rust/src/bin/server/main.rs
backend-rust/src/bin/server/s_course.rs
backend-rust/src/bin/server/s_get_modules.rs
backend-rust/src/bin/server/s_module.rs
backend-rust/src/bin/server/s_my_modules.rs
backend-rust/src/bin/server/s_search_course.rs
backend-rust/src/bin/server/s_search_module.rs
backend-rust/src/bin/server/s_setup.rs
backend-rust/src/tucan_user.rs
frontend-react/src/Navigation.tsx
frontend-react/src/api_base.ts
frontend-react/src/components/SearchPage.tsx
frontend-react/src/routes/Course.tsx
frontend-react/src/routes/Login.tsx
frontend-react/src/routes/Logout.tsx
frontend-react/src/routes/Module.tsx
frontend-react/src/routes/Modules.tsx
frontend-react/src/routes/MyModules.tsx
frontend-react/src/routes/Welcome.tsx

Fixes https://github.com/mohe2015/tucant/issues/51

Handle expired sessions and generally unauthorized responses

---

backend-rust/src/bin/server/s_setup.rs
frontend-react/src/components/SearchPage.tsx
frontend-react/src/routes/InitialFetch.tsx
frontend-react/src/routes/Login.tsx

Closes https://github.com/mohe2015/tucant/issues/37
Fixes https://github.com/mohe2015/tucant/issues/56

Add loading indicators

---

backend-rust/migrations/2022-09-10-005633_initial/up.sql
backend-rust/src/bin/server/main.rs
backend-rust/src/bin/server/s_course.rs
backend-rust/src/bin/server/s_get_modules.rs
backend-rust/src/bin/server/s_module.rs
backend-rust/src/bin/server/s_my_modules.rs
backend-rust/src/bin/server/s_search_course.rs
backend-rust/src/bin/server/s_search_module.rs
backend-rust/src/models.rs
backend-rust/src/schema.rs
backend-rust/src/tucan.rs
backend-rust/src/tucan_user.rs

Store my modules in db

---

.github/workflows/rust.yml
Cargo.lock
README.md
backend-rust/Cargo.toml
backend-rust/src/bin/server/main.rs
backend-rust/src/bin/server/s_course.rs
backend-rust/src/bin/server/s_get_modules.rs
backend-rust/src/bin/server/s_module.rs
backend-rust/src/bin/server/s_my_courses.rs
backend-rust/src/bin/server/s_my_modules.rs
backend-rust/src/bin/server/s_search_course.rs
backend-rust/src/bin/server/s_search_module.rs
backend-rust/src/bin/server/s_setup.rs
backend-rust/src/tucan.rs
backend-rust/src/tucan_user.rs

Open Telemetry

---

.github/workflows/rust.yml
README.md
backend-rust/src/bin/server/main.rs
backend-rust/src/models.rs
backend-rust/src/tucan.rs
backend-rust/src/typescript.rs

Implement login hack using bookmarklet

---

backend-rust/migrations/2022-09-10-005633_initial/up.sql
backend-rust/src/bin/server/s_get_modules.rs
backend-rust/src/bin/server/s_setup.rs
backend-rust/src/models.rs
backend-rust/src/schema.rs
backend-rust/src/tucan_user.rs
frontend-react/src/api.ts
frontend-react/src/components/ModuleList.tsx

Fixes https://github.com/mohe2015/tucant/issues/98

Allow submodules and submenus at the same time in registrations

---

Cargo.lock
backend-rust/Cargo.toml
backend-rust/src/bin/test/main.rs
backend-rust/src/bin/test_client/main.rs
backend-rust/src/tucan_user.rs
backend-rust/src/url.rs

Closes https://github.com/mohe2015/tucant/issues/10

Start implementing fetching exams

---

backend-rust/Dockerfile-opensearch
backend-rust/src/bin/server/s_coursegroup.rs
backend-rust/src/tucan_user.rs
frontend-react/src/api.ts
frontend-react/src/routes/CourseGroup.tsx
frontend-react/src/routes/MyCourses.tsx

Implement showing Übungstermine

---

.cargo/config.toml
.github/workflows/rust.yml
Cargo.lock
Cargo.toml
backend-rust-derive-lib/Cargo.toml
backend-rust-derive/src/lib.rs
backend-rust/Cargo.toml
backend-rust/src/bin/opensearch_indexer/main.rs
backend-rust/src/bin/server/main.rs
backend-rust/src/bin/server/s_course.rs
backend-rust/src/bin/server/s_coursegroup.rs
backend-rust/src/bin/server/s_exam.rs
backend-rust/src/bin/server/s_get_modules.rs
backend-rust/src/bin/server/s_module.rs
backend-rust/src/bin/server/s_search_module.rs
backend-rust/src/models.rs
backend-rust/src/tucan_user.rs
debug-adapter-protocol-macro-impl/src/utils.rs
deny.toml
rust-toolchain.toml
tucant-language-server/Cargo.toml
tucant-language-server/src/bin/language-server/main.rs
tucant-language/Untitled.ipynb
tucant-vscode/CONTRIBUTING.md

TODO: Disable default features everywhere
TODO: Remove dependencies that are not strictly required (language server should probably not depend on tucant itself etc)

Reduce dependencies

---

Cargo.lock
backend-rust-derive-lib/Cargo.toml
backend-rust-derive/Cargo.toml
backend-rust/Cargo.toml
backend-rust/src/bin/opensearch_indexer/main.rs
backend-rust/src/bin/server/main.rs
backend-rust/src/bin/test/main.rs
backend-rust/src/tucan_user.rs
debug-adapter-protocol-macro-impl/Cargo.toml
debug-adapter-protocol-macro-impl/src/json_schema.rs
debug-adapter-protocol/Cargo.toml
debug-adapter-protocol/build.rs
debug-adapter-protocol/src/main.rs
frontend-yew/Cargo.toml
json-rpc-server/Cargo.toml
out-dir-include/Cargo.toml
tucant-language-server-derive-internal/Cargo.toml
tucant-language-server-derive-output/Cargo.toml
tucant-language-server/Cargo.toml
tucant-language-server/src/bin/language-server/main.rs

Revert "Reduce dependencies"

---

tucan-connector/src/bin/converter/main.rs
tucan-connector/src/externalpages/studveranst.rs
tucan-connector/src/lib.rs
tucan-connector/src/main.rs
tucan-connector/src/mlsstart/start_page.rs
tucan-connector/src/moduledetails.rs
tucan-connector/src/moduledetails/index.rs
tucan-connector/src/registration/index.rs
tucan-connector/src/root.rs
tucan-connector/src/startpage_dispatch/after_login.rs
tucan-connector/src/startpage_dispatch/one.rs
tucan-injector/src/lib.rs

Closes https://github.com/tucant/tucant/issues/416

Partial module details parsing

---

README.md
crates/tucan-connector/src/lib.rs
crates/tucan-connector/src/mymodules.rs
crates/tucan-connector/src/registration/index.rs
crates/tucant-api/src/lib.rs
crates/tucant-types/src/lib.rs
crates/tucant-types/src/moduledetails.rs
crates/tucant-types/src/mymodules.rs
crates/tucant-yew/src/api_server.rs
crates/tucant-yew/src/lib.rs
crates/tucant-yew/src/my_modules.rs
crates/tucant-yew/src/navbar_logged_in.rs
crates/tucant-yew/src/tauri.rs

Close https://github.com/tucant/tucant/issues/504

Parse mymodules

---

crates/tucan-connector/src/lib.rs
crates/tucan-connector/src/mycourses.rs
crates/tucan-connector/src/mymodules.rs
crates/tucant-api/src/lib.rs
crates/tucant-types/src/coursedetails.rs
crates/tucant-types/src/lib.rs
crates/tucant-types/src/mycourses.rs
crates/tucant-types/src/mymodules.rs
crates/tucant-yew/src/api_server.rs
crates/tucant-yew/src/lib.rs
crates/tucant-yew/src/my_courses.rs
crates/tucant-yew/src/navbar_logged_in.rs
crates/tucant-yew/src/tauri.rs

Close https://github.com/tucant/tucant/issues/501

Implement Meine Veranstaltungen

---

crates/tucan-connector/src/lib.rs
crates/tucan-connector/src/myexams.rs
crates/tucant-api/src/lib.rs
crates/tucant-types/src/lib.rs
crates/tucant-types/src/myexams.rs
crates/tucant-yew/src/api_server.rs
crates/tucant-yew/src/lib.rs
crates/tucant-yew/src/my_exams.rs
crates/tucant-yew/src/navbar_logged_in.rs
crates/tucant-yew/src/tauri.rs

Close https://github.com/tucant/tucant/issues/503

Parse Meine Prüfungen

---

crates/tucan-connector/src/courseresults.rs
crates/tucan-connector/src/examresults.rs
crates/tucan-connector/src/lib.rs
crates/tucan-connector/src/mydocuments.rs
crates/tucant-api/src/lib.rs
crates/tucant-types/src/courseresults.rs
crates/tucant-types/src/examresults.rs
crates/tucant-types/src/lib.rs
crates/tucant-types/src/mydocuments.rs
crates/tucant-yew/src/api_server.rs
crates/tucant-yew/src/course_results.rs
crates/tucant-yew/src/exam_results.rs
crates/tucant-yew/src/lib.rs
crates/tucant-yew/src/my_documents.rs
crates/tucant-yew/src/navbar_logged_in.rs
crates/tucant-yew/src/tauri.rs
tucant-extension/manifest.json

Fixes https://github.com/tucant/tucant/issues/500
Fixes https://github.com/tucant/tucant/issues/499
Fixes https://github.com/tucant/tucant/issues/502

More pages

---

.vscode/settings.json
Cargo.lock
crates/key-value-database/Cargo.toml
crates/key-value-database/src/lib.rs
crates/tucan-connector/src/lib.rs

See https://github.com/launchbadge/sqlx/issues/2510

Fix running tests with buggy sqlx

---

README.md
bacon.toml
crates/tucan-connector/src/mlsstart/start_page.rs
crates/tucan-connector/src/myexams.rs
crates/tucant-types/src/coursedetails.rs
crates/tucant-types/src/mlsstart.rs
crates/tucant-types/src/myexams.rs
crates/tucant-yew/Trunk.toml
crates/tucant-yew/src/common.rs
crates/tucant-yew/src/course_results.rs
crates/tucant-yew/src/exam_results.rs
crates/tucant-yew/src/my_courses.rs
crates/tucant-yew/src/my_exams.rs
crates/tucant-yew/src/my_modules.rs
crates/tucant-yew/src/navbar.rs
tucant-extension/manifest.json

Fixes https://github.com/tucant/tucant/issues/550

More linking

---

README.md
crates/tucant-types/src/lib.rs
crates/tucant-types/src/moduledetails.rs
crates/tucant-types/src/mymodules.rs
crates/tucant-yew/src/lib.rs
crates/tucant-yew/src/my_semester_modules.rs
crates/tucant-yew/src/navbar_logged_in.rs

Fixes https://github.com/tucant/tucant/issues/568

My modules single semester

---

crates/tucan-connector/src/coursedetails/index.rs
crates/tucan-connector/src/examresults.rs
crates/tucan-connector/src/mycourses.rs
crates/tucan-connector/src/mymodules.rs
crates/tucant-types/src/examresults.rs
crates/tucant-yew/src/navbar_logged_in.rs
tucant-extension/background.js
tucant-extension/manifest.json

Fixes https://github.com/tucant/tucant/issues/571

Small fixes

---

.vscode/settings.json
crates/tucan-plus-dioxus/Cargo.lock
crates/tucan-plus-dioxus/Cargo.toml
crates/tucan-plus-dioxus/diesel.toml
crates/tucan-plus-dioxus/src/lib.rs
crates/tucan-plus-dioxus/src/login_component.rs
crates/tucan-plus-dioxus/src/logout_component.rs
crates/tucan-plus-dioxus/src/main.rs
crates/tucan-plus-dioxus/src/planning.rs
crates/tucan-plus-dioxus/src/planning/load_leistungsspiegel.rs
crates/tucan-plus-dioxus/src/planning/load_semesters.rs
crates/tucan-plus-worker/Cargo.lock
crates/tucan-plus-worker/Cargo.toml
crates/tucan-plus-worker/src/lib.rs
crates/tucan-plus-worker/src/main.rs
flake.nix

Closes https://github.com/tucan-plus/tucan-plus/issues/683
Form inputs broken
keyring not working
use https://crates.io/crates/keyring-core and https://crates.io/crates/android-native-keyring-store

Support native and android again
